import { ethers, network, run } from 'hardhat'
import fs from 'fs'
import path from 'path'

async function main() {
  const [deployer] = await ethers.getSigners()
  const deployerAddr = await deployer.getAddress()
  const balance = await ethers.provider.getBalance(deployerAddr)

  console.log('\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━')
  console.log('  Wallad — PhysicalWallEscrow Deployment')
  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━')
  console.log(`  Network  : ${network.name} (chainId: ${network.config.chainId})`)
  console.log(`  Deployer : ${deployerAddr}`)
  console.log(`  Balance  : ${ethers.formatEther(balance)} BNB`)
  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n')

  if (balance < ethers.parseEther('0.01')) {
    throw new Error(
      `Insufficient balance. Need at least 0.01 BNB for deployment.\n` +
      `Get testnet BNB at: https://testnet.binance.org/faucet-smart`
    )
  }

  // ── Deploy ──────────────────────────────────────────────────────────────
  console.log('Deploying PhysicalWallEscrow...')
  const factory = await ethers.getContractFactory('PhysicalWallEscrow')
  const escrow  = await factory.deploy()
  await escrow.waitForDeployment()

  const address = await escrow.getAddress()
  const deployTx = escrow.deploymentTransaction()
  const receipt  = await deployTx?.wait()

  console.log(`\n✅ Deployed successfully!`)
  console.log(`   Contract : ${address}`)
  console.log(`   Tx Hash  : ${deployTx?.hash}`)
  console.log(`   Gas Used : ${receipt?.gasUsed.toString()}`)
  console.log(`   Block    : ${receipt?.blockNumber}`)

  // ── Verify contract constants ────────────────────────────────────────────
  const proofDeadline   = await escrow.DEFAULT_PROOF_DEADLINE()
  const disputeWindow   = await escrow.DEFAULT_DISPUTE_WINDOW()
  console.log(`\n   DEFAULT_PROOF_DEADLINE : ${proofDeadline / BigInt(86400)} days`)
  console.log(`   DEFAULT_DISPUTE_WINDOW  : ${disputeWindow / BigInt(86400)} days`)

  // ── Write deployment artifact ────────────────────────────────────────────
  const artifact = {
    network:      network.name,
    chainId:      network.config.chainId,
    address,
    txHash:       deployTx?.hash,
    blockNumber:  receipt?.blockNumber,
    gasUsed:      receipt?.gasUsed?.toString(),
    deployer:     deployerAddr,
    deployedAt:   new Date().toISOString(),
  }

  const artifactDir  = path.join(__dirname, '../deployments')
  const artifactPath = path.join(artifactDir, `${network.name}.json`)
  fs.mkdirSync(artifactDir, { recursive: true })
  fs.writeFileSync(artifactPath, JSON.stringify(artifact, null, 2))
  console.log(`\n   Artifact saved → ${artifactPath}`)

  // ── Write address to web app .env.local ─────────────────────────────────
  const webEnvPath = path.join(__dirname, '../../web/.env.local')
  const envContent = `# Auto-generated by deploy script\nNEXT_PUBLIC_ESCROW_ADDRESS=${address}\nNEXT_PUBLIC_CHAIN_ID=${network.config.chainId}\n`
  fs.writeFileSync(webEnvPath, envContent)
  console.log(`   Web .env.local updated → ${webEnvPath}`)

  // ── BscScan verification (non-blocking) ─────────────────────────────────
  if (network.name !== 'localhost' && network.name !== 'hardhat') {
    console.log('\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━')
    console.log('  Verifying on BscScan (waiting 6 confirmations)...')
    try {
      await deployTx?.wait(6)
      await run('verify:verify', {
        address,
        constructorArguments: [],
      })
      const explorerBase =
        network.name === 'bscTestnet'
          ? 'https://testnet.bscscan.com'
          : 'https://bscscan.com'
      console.log(`✅ Verified: ${explorerBase}/address/${address}#code`)
    } catch (e: unknown) {
      const msg = e instanceof Error ? e.message : String(e)
      console.log(`⚠️  Verification failed (non-fatal): ${msg}`)
      console.log('   Retry manually: npx hardhat verify --network bscTestnet', address)
    }
  }

  console.log('\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━')
  console.log('  Next steps:')
  console.log('  1. Copy NEXT_PUBLIC_ESCROW_ADDRESS to web/.env.local (done above)')
  console.log('  2. Run: cd web && npm run dev')
  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n')
}

main().catch((e) => {
  console.error(e)
  process.exit(1)
})
